import Head from 'next/head';
import { css } from '@emotion/react';
import { Header } from '@/components/ui/Header';
import { Footer } from '@/components/ui/Footer';

const WrapperStyle = css`
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: auto 1fr auto;
  min-height: var(--window-h, 100vh);
`;

type Props = {
  title: string;
  children: React.ReactNode;
};
export const TopLayout: React.FC<Props> = ({ title, children }) => {
  return (
    <div css={WrapperStyle}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
};
